test_analysis = {"analysis": {"kr20": -1.167,
                                 "idr": {"1": 0.0, "2": 0.0, "3": 0.082, "4": 0.082, "5": 0.082, "6": 0.0, "7": -0.082},
                                 "difficulty": {"1": 0.667, "2": 0.333, "3": 0.333, "4": 0.333, "5": 0.667, "6": 0.0, "7": 0.667}, 
                                 "scores": {"1234": 57.1, "1235": 71.4, "1236": 42.9},
                                 "average": 57.1,
                                 "weighted_scores": {"1234": 44.4, "1235": 55.5, "1236": 33.3},
                                 "weighted_avg": 44.4, 
                                 "exclude": ["7"],
                                 "diff_avg": 0.429, 
                                 "idr_avg": 0.023, 
                                 "num_correct": {"1": 1, "2": 2, "3": 2, "4": 2, "5": 1, "6": 3, "7": 1},
                                 "assumptions": {"1234": ["7"], "1235": ["7"]},
                                 "topic_rights": {"1234": [[{"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Nucleus"),
                                                               (5,
                                                                "DNA")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Ribosomes")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "E"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "e")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "K"),
                                                               (5,
                                                                "l")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "k")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "Q"),
                                                               (5,
                                                                "r")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 2},
                                          {"topic_hierarchy": ((0,
                                                                "m"),
                                                               (1,
                                                                "n"),
                                                               (2,
                                                                "o"),
                                                               (3,
                                                                "p"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "a"),
                                                               (1,
                                                                "b"),
                                                               (2,
                                                                "c"),
                                                               (3,
                                                                "d"),
                                                               (4,
                                                                "e"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 1}]],
                                "1235": [[{"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Nucleus"),
                                                               (5,
                                                                "DNA")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Ribosomes")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "E"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 2},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "e")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "K"),
                                                               (5,
                                                                "l")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "k")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "Q"),
                                                               (5,
                                                                "r")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 2},
                                          {"topic_hierarchy": ((0,
                                                                "m"),
                                                               (1,
                                                                "n"),
                                                               (2,
                                                                "o"),
                                                               (3,
                                                                "p"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "a"),
                                                               (1,
                                                                "b"),
                                                               (2,
                                                                "c"),
                                                               (3,
                                                                "d"),
                                                               (4,
                                                                "e"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 1}]],
                                "1236": [[{"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Nucleus"),
                                                               (5,
                                                                "DNA")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "Biology"),
                                                               (1,
                                                                "Cell biology"),
                                                               (2,
                                                                "Cells"),
                                                               (3,
                                                                "Organelles"),
                                                               (4,
                                                                "Ribosomes")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "E"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "A"),
                                                               (1,
                                                                "B"),
                                                               (2,
                                                                "C"),
                                                               (3,
                                                                "D"),
                                                               (4,
                                                                "e")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "K"),
                                                               (5,
                                                                "l")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "G"),
                                                               (1,
                                                                "H"),
                                                               (2,
                                                                "I"),
                                                               (3,
                                                                "J"),
                                                               (4,
                                                                "k")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "Q"),
                                                               (5,
                                                                "r")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "M"),
                                                               (1,
                                                                "N"),
                                                               (2,
                                                                "O"),
                                                               (3,
                                                                "P"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 1},
                                          {"topic_hierarchy": ((0,
                                                                "m"),
                                                               (1,
                                                                "n"),
                                                               (2,
                                                                "o"),
                                                               (3,
                                                                "p"),
                                                               (4,
                                                                "q")),
                                           "topic_rights": 0},
                                          {"topic_hierarchy": ((0,
                                                                "a"),
                                                               (1,
                                                                "b"),
                                                               (2,
                                                                "c"),
                                                               (3,
                                                                "d"),
                                                               (4,
                                                                "e"),
                                                               (5,
                                                                "f")),
                                           "topic_rights": 1}]]},
                                 "grad_year_analysis": {
                                    "2022": {
                                        "kr20": -2.333, 
                                        "idr": {"1": -0.036, "2": 0.036, "3": 0.0, "4": 0.0, "5": 0.036, "6": 0.0, "7": 0.0}, 
                                        "difficulty": {"1": 0.5, "2": 0.5,"3": 0.0, "4": 0.0, "5": 0.5, "6": 0.0, "7": 1.0}, 
                                        "scores": {"1234": 57.1, "1235": 71.4}, 
                                        "average": 64.2, 
                                        "weighted_scores": {"1234": 20.0, "1235": 40.0},
                                        "weighted_avg": 30.0,
                                        "exclude": ["1"],
                                        "diff_avg": 0.357,
                                        "idr_avg": 0.005,
                                        "num_correct": {"1": 1, "2": 1, "3": 2, "4": 2, "5": 1, "6": 2, "7": 0},
                                        "assumptions": {"1234": ["7"], "1235": ["7"]},
                                        "topic_rights": {"1234": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]],
                            "1235": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]],
                            "1236": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]]},
                                    },
                                    "2024": "Invalid data - Not enough students"
                                 }
                                }
                    }

grad_analysis = {"2022": {
                        "kr20": -2.333, 
                        "idr": {"1": -0.036, "2": 0.036, "3": 0.0, "4": 0.0, "5": 0.036, "6": 0.0, "7": 0.0}, 
                        "difficulty": {"1": 0.5, "2": 0.5,"3": 0.0, "4": 0.0, "5": 0.5, "6": 0.0, "7": 1.0}, 
                        "scores": {"1234": 57.1, "1235": 71.4}, 
                        "average": 64.2, 
                        "weighted_scores": {"1234": 20.0, "1235": 40.0},
                        "weighted_avg": 30.0,
                        "exclude": ["1"],
                        "diff_avg": 0.357,
                        "idr_avg": 0.005,
                        "num_correct": {"1": 1, "2": 1, "3": 2, "4": 2, "5": 1, "6": 2, "7": 0},
                        "assumptions": {"1234": ["7"], "1235": ["7"]},
                        "topic_rights": {"1234": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]],
                            "1235": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 2},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]],
                            "1236": [[{"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Nucleus"),
                                                           (5,
                                                            "DNA")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "Biology"),
                                                           (1,
                                                            "Cell biology"),
                                                           (2,
                                                            "Cells"),
                                                           (3,
                                                            "Organelles"),
                                                           (4,
                                                            "Ribosomes")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "E"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "A"),
                                                           (1,
                                                            "B"),
                                                           (2,
                                                            "C"),
                                                           (3,
                                                            "D"),
                                                           (4,
                                                            "e")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "K"),
                                                           (5,
                                                            "l")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "G"),
                                                           (1,
                                                            "H"),
                                                           (2,
                                                            "I"),
                                                           (3,
                                                            "J"),
                                                           (4,
                                                            "k")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "Q"),
                                                           (5,
                                                            "r")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "M"),
                                                           (1,
                                                            "N"),
                                                           (2,
                                                            "O"),
                                                           (3,
                                                            "P"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 1},
                                      {"topic_hierarchy": ((0,
                                                            "m"),
                                                           (1,
                                                            "n"),
                                                           (2,
                                                            "o"),
                                                           (3,
                                                            "p"),
                                                           (4,
                                                            "q")),
                                       "topic_rights": 0},
                                      {"topic_hierarchy": ((0,
                                                            "a"),
                                                           (1,
                                                            "b"),
                                                           (2,
                                                            "c"),
                                                           (3,
                                                            "d"),
                                                           (4,
                                                            "e"),
                                                           (5,
                                                            "f")),
                                       "topic_rights": 1}]]},
                        },
                    "2024": "Invalid data - Not enough students"
                    }

topic_score = {"1234": [[
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Nucleus"),
                                            (5, "DNA")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Ribosomes")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "E"),
                                            (5, "f")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "e")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "K"),
                                            (5, "l")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "k")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "Q"),
                                            (5, "r")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "q")),
                        "topic_rights": 2},
                        {"topic_hierarchy": ((0, "m"),
                                            (1, "n"),
                                            (2, "o"),
                                            (3, "p"),
                                            (4, "q")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "a"),
                                            (1, "b"),
                                            (2, "c"),
                                            (3, "d"),
                                            (4, "e"),
                                            (5, "f")),
                        "topic_rights": 1}]],
                    "1235": [[
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Nucleus"),
                                            (5, "DNA")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Ribosomes")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "E"),
                                            (5, "f")),
                        "topic_rights": 2},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "e")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "K"),
                                            (5, "l")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "k")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "Q"),
                                            (5, "r")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "q")),
                        "topic_rights": 2},
                        {"topic_hierarchy": ((0, "m"),
                                            (1, "n"),
                                            (2, "o"),
                                            (3, "p"),
                                            (4, "q")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "a"),
                                            (1, "b"),
                                            (2, "c"),
                                            (3, "d"),
                                            (4, "e"),
                                            (5, "f")),
                        "topic_rights": 1}]],
                    "1236": [[
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Nucleus"),
                                            (5, "DNA")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "Biology"),
                                            (1, "Cell biology"),
                                            (2, "Cells"),
                                            (3, "Organelles"),
                                            (4, "Ribosomes")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "E"),
                                            (5, "f")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "A"),
                                            (1, "B"),
                                            (2, "C"),
                                            (3, "D"),
                                            (4, "e")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "K"),
                                            (5, "l")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "G"),
                                            (1, "H"),
                                            (2, "I"),
                                            (3, "J"),
                                            (4, "k")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "Q"),
                                            (5, "r")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "M"),
                                            (1, "N"),
                                            (2, "O"),
                                            (3, "P"),
                                            (4, "q")),
                        "topic_rights": 1},
                        {"topic_hierarchy": ((0, "m"),
                                            (1, "n"),
                                            (2, "o"),
                                            (3, "p"),
                                            (4, "q")),
                        "topic_rights": 0},
                        {"topic_hierarchy": ((0, "a"),
                                            (1, "b"),
                                            (2, "c"),
                                            (3, "d"),
                                            (4, "e"),
                                            (5, "f")),
                        "topic_rights": 1}]]}